# Build stage
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build

# Production stage
FROM node:22-alpine
WORKDIR /app
COPY package*.json yarn.lock ./
RUN yarn install --production
COPY --from=builder /app/dist ./dist
COPY views ./views
CMD ["node", "./dist/main.js"]
